{{- if and .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "app.fullname" . }}-{{ .Values.externalSecret.suffix }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStore }}
    kind: {{ .Values.externalSecret.kind | default "ClusterSecretStore" }}
  target:
    name: {{ include "app.fullname" . }}-{{ .Values.externalSecret.suffix }}
    creationPolicy: {{ .Values.externalSecret.creationPolicy | default "Owner"}}
  dataFrom:
  - extract:
      key: {{ .Values.externalSecret.secretPath }}
{{- end }}