{{- if .Values.serviceMonitor.enabled }}
{{- $endpoints := .Values.serviceMonitor.endpoints }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "app.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    prometheus: {{ .Values.serviceMonitor.prometheusName }}
    {{- include "app.labels" . | nindent 4 }}
  {{- with .Values.serviceMonitor.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.serviceMonitor.namespaceSelector }}
  namespaceSelector:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
  {{- with .Values.serviceMonitor.matchLabels }}
    matchLabels:
      {{- toYaml . | nindent 6 }}
  {{- end }}
  endpoints:
    {{- range $k, $v := $endpoints }}
    - port: {{ $v.port | default "metrics" }}
      path: {{ $v.path | default "/metrics" }}
      interval: {{ $v.interval | default "60s" }}
      honorLabels: {{ $v.honorLabels | default "true"  }}
      scrapeTimeout: {{ $v.scrapeTimeout | default "30s" }}
      {{- with $v.relabelings }}
      relabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $v.metricRelabelings }}
      metricRelabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
{{- end }}