nameOverride: &nameOverride "my-service"
fullnameOverride: &fullnameOverride "my-service"
cluster: &cluster "dev"
environment: &environment "dev"

deployment:
  service:
      containerPort: 8080
  image:
    repository: nginx
    tag: latest
  migrationjob:
    enabled: true
ingress:
  enabled: false

externalSecret:
  enabled: false

persistence:
  enabled: false
