apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world
  namespace: argocd
spec:
  syncPolicy:
    automated: {}
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: default
  source:
    path:    myfirstdeployment/helm
    repoURL: git@github.com:waseemhaddad52/haddad.git
    targetRevision: main
