apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-list-deployment
  labels:
    app: todo-list
spec:
  replicas: 2  # Number of replicas (pods) to be created
  selector:
    matchLabels:
      app: todo-list
  template:
    metadata:
      labels:
        app: todo-list
    spec:
      containers:
      - name: todo-list-container
        image: 727245885999.dkr.ecr.us-east-2.amazonaws.com/waseem-ecr:dev_27  # Make sure this image tag exists in your ECR
        ports:
        - containerPort: 80  # HTTP server port
        - containerPort: 3306  # Database port (MySQL, if relevant)
        env:
        - name: ENV_NAME
          value: "dev"  # Define any environment variables you need
