apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todo-ingress
  annotations:
    nginx.ingress.kubernetes.io/configuration-snippet: |
        add_header Content-Security-Policy "upgrade-insecure-requests";
        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    nginx.ingress.kubernetes.io/cors-allow-origin: '*'
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - host: waseem-todo.slashtec.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: todo-list-service
            port:
              number: 80
