{{- if .Values.goDBMigration.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "app.fullname" . }}-db-migration
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  secretStoreRef:
    name: {{ .Values.goDBMigration.externalSecret.secretStore }}
    kind: {{ .Values.goDBMigration.externalSecret.kind | default "ClusterSecretStore" }}
  target:
    name: {{ include "app.fullname" . }}-db-migration
    creationPolicy: {{ .Values.goDBMigration.externalSecret.creationPolicy | default "Owner"}}
  data:
  {{- with .Values.goDBMigration.externalSecret.secrets }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}