apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  refreshInterval: 10s
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-store         
  target:
    name: {{ include "app.fullname" . }}
    creationPolicy: {{ .Values.externalSecretgcp.creationPolicy | default "Owner"}}
  dataFrom:
  - extract:
      key: {{ .Values.externalSecretgcp.name }}
