{{- if .Values.deployment.migrationjob.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  generateName: {{ include "app.fullname" . }}-migration-
  annotations:
    argocd.argoproj.io/hook: "PreSync"
    argocd.argoproj.io/hook-delete-policy: "BeforeHookCreation"
    argocd.argoproj.io/job-cleanup: "keep"
spec:
  template:
    spec:
      containers:
      - name: {{ include "app.name" . }}-migration
        image: "{{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag | default .Chart.AppVersion }}"
        command:
          - "php"
          - "artisan"
          - "migrate"
      restartPolicy: Never
  backoffLimit: 0
{{- end }}
